name: BootstrapVideoEmbed
version: 1.0.0
description: A tag that outputs your video embeds in the Bootstrap responsive format.
url: https://github.com/jrc9designstudio/statamic-bootstrap-video-embed
developer: JRC9 Design Studio
developer_url: https://jrc9.ca
